### 회원가입
POST http://localhost:8080/account
Content-Type: application/json

{
  "account":"huning@gmail.com",
  "password":"1234"
}

### 회원 정보
GET http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 회원 탈퇴
DELETE http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}

> {%
client.global.set("accessToken", '');
client.global.set("refreshToken", '');
%}